CFLAGS = -std=gnu99
LEX = flex

parse_test: parse_test.o parse.tab.o token.o

parse_test.o: parse_test.c lsystem.h parse.tab.h

parse.tab.c parse.tab.h: parse.y
	bison -d parse.y

parse.tab.o: parse.tab.c lsystem.h

token.c: token.l
token.o: token.c parse.tab.h

clean:
	rm -f *.o parse_test parse.tab.[ch] token.c
